version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - ./.env
    networks:
      - api

  test-db:
    container_name: test-db
    image: postgres:13
    ports:
      - 5435:5432
    env_file:
      - ./.env.test
    networks:
      - api

  pgadmin:
    container_name: pg-admin
    links:
      - postgres:postgres
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  pgadmin:
    driver: local
  redis:
    driver: local
networks:
  api:
  postgres:
    driver: bridge
